const SCREEN_WIDTH = 300;
const SCREEN_HEIGHT = 140;
const VISION_ANGLE = 80;

const MINIMAP_BASE_X = 16;
const MINIMAP_BASE_Y = 16;

export {
  SCREEN_WIDTH,
  SCREEN_HEIGHT,
  VISION_ANGLE,
  MINIMAP_BASE_X,
  MINIMAP_BASE_Y,
}